INSERT INTO `t_location` VALUES ('上海市');
INSERT INTO `t_location` VALUES ('内蒙古省乌兰察布市 ');
INSERT INTO `t_location` VALUES ('内蒙古省乌海市');
INSERT INTO `t_location` VALUES ('内蒙古省包头市');
INSERT INTO `t_location` VALUES ('内蒙古省呼伦贝尔市');
INSERT INTO `t_location` VALUES ('内蒙古省呼和浩特市');
INSERT INTO `t_location` VALUES ('内蒙古省巴彦淖尔市');
INSERT INTO `t_location` VALUES ('内蒙古省赤峰市');
INSERT INTO `t_location` VALUES ('内蒙古省通辽市');
INSERT INTO `t_location` VALUES ('内蒙古省鄂尔多斯市');
INSERT INTO `t_location` VALUES ('北京市');
INSERT INTO `t_location` VALUES ('吉林省吉林市');
INSERT INTO `t_location` VALUES ('吉林省四平市');
INSERT INTO `t_location` VALUES ('吉林省松原市 ');
INSERT INTO `t_location` VALUES ('吉林省白城市');
INSERT INTO `t_location` VALUES ('吉林省白山市');
INSERT INTO `t_location` VALUES ('吉林省辽源市');
INSERT INTO `t_location` VALUES ('吉林省通化市');
INSERT INTO `t_location` VALUES ('天津市');
INSERT INTO `t_location` VALUES ('山西省临汾市');
INSERT INTO `t_location` VALUES ('山西省吕梁市');
INSERT INTO `t_location` VALUES ('山西省大同市');
INSERT INTO `t_location` VALUES ('山西省太原市');
INSERT INTO `t_location` VALUES ('山西省忻州市');
INSERT INTO `t_location` VALUES ('山西省晋中市');
INSERT INTO `t_location` VALUES ('山西省晋城市 ');
INSERT INTO `t_location` VALUES ('山西省朔州市');
INSERT INTO `t_location` VALUES ('山西省运城市');
INSERT INTO `t_location` VALUES ('山西省长治市');
INSERT INTO `t_location` VALUES ('山西省阳泉市 ');
INSERT INTO `t_location` VALUES ('广东省东莞市');
INSERT INTO `t_location` VALUES ('广东省中山市');
INSERT INTO `t_location` VALUES ('广东省云浮市');
INSERT INTO `t_location` VALUES ('广东省佛山市');
INSERT INTO `t_location` VALUES ('广东省惠州市');
INSERT INTO `t_location` VALUES ('广东省揭阳市');
INSERT INTO `t_location` VALUES ('广东省汕头市');
INSERT INTO `t_location` VALUES ('广东省汕尾市');
INSERT INTO `t_location` VALUES ('广东省江门市');
INSERT INTO `t_location` VALUES ('广东省河源市');
INSERT INTO `t_location` VALUES ('广东省清远市');
INSERT INTO `t_location` VALUES ('广东省湛江市');
INSERT INTO `t_location` VALUES ('广东省潮州市');
INSERT INTO `t_location` VALUES ('广东省珠海市');
INSERT INTO `t_location` VALUES ('广东省肇庆市');
INSERT INTO `t_location` VALUES ('广东省茂名市');
INSERT INTO `t_location` VALUES ('广东省阳江市');
INSERT INTO `t_location` VALUES ('广东省韶关市');
INSERT INTO `t_location` VALUES ('江苏省南京市');
INSERT INTO `t_location` VALUES ('江苏省南通市');
INSERT INTO `t_location` VALUES ('江苏省宿迁市');
INSERT INTO `t_location` VALUES ('江苏省常州市');
INSERT INTO `t_location` VALUES ('江苏省徐州市');
INSERT INTO `t_location` VALUES ('江苏省扬州市');
INSERT INTO `t_location` VALUES ('江苏省无锡市');
INSERT INTO `t_location` VALUES ('江苏省泰州市');
INSERT INTO `t_location` VALUES ('江苏省淮安市');
INSERT INTO `t_location` VALUES ('江苏省盐城市');
INSERT INTO `t_location` VALUES ('江苏省苏州市');
INSERT INTO `t_location` VALUES ('江苏省连云港市');
INSERT INTO `t_location` VALUES ('江苏省镇江市');
INSERT INTO `t_location` VALUES ('河北省保定市');
INSERT INTO `t_location` VALUES ('河北省唐山市');
INSERT INTO `t_location` VALUES ('河北省廊坊市');
INSERT INTO `t_location` VALUES ('河北省张家口市 ');
INSERT INTO `t_location` VALUES ('河北省承德市 ');
INSERT INTO `t_location` VALUES ('河北省沧州市');
INSERT INTO `t_location` VALUES ('河北省石家庄市');
INSERT INTO `t_location` VALUES ('河北省秦皇岛市');
INSERT INTO `t_location` VALUES ('河北省衡水市');
INSERT INTO `t_location` VALUES ('河北省邢台市 ');
INSERT INTO `t_location` VALUES ('河北省邯郸市 ');
INSERT INTO `t_location` VALUES ('浙江省丽水市');
INSERT INTO `t_location` VALUES ('浙江省台州市');
INSERT INTO `t_location` VALUES ('浙江省嘉兴市');
INSERT INTO `t_location` VALUES ('浙江省杭州市');
INSERT INTO `t_location` VALUES ('浙江省温州市');
INSERT INTO `t_location` VALUES ('浙江省湖州市');
INSERT INTO `t_location` VALUES ('浙江省绍兴市');
INSERT INTO `t_location` VALUES ('浙江省舟山市');
INSERT INTO `t_location` VALUES ('浙江省衢州市');
INSERT INTO `t_location` VALUES ('浙江省金华市');
INSERT INTO `t_location` VALUES ('深圳市');
INSERT INTO `t_location` VALUES ('辽宁省丹东市');
INSERT INTO `t_location` VALUES ('辽宁省抚顺市');
INSERT INTO `t_location` VALUES ('辽宁省朝阳市');
INSERT INTO `t_location` VALUES ('辽宁省本溪市 ');
INSERT INTO `t_location` VALUES ('辽宁省盘锦市');
INSERT INTO `t_location` VALUES ('辽宁省营口市 ');
INSERT INTO `t_location` VALUES ('辽宁省葫芦岛');
INSERT INTO `t_location` VALUES ('辽宁省辽阳市');
INSERT INTO `t_location` VALUES ('辽宁省铁岭市 ');
INSERT INTO `t_location` VALUES ('辽宁省锦州市');
INSERT INTO `t_location` VALUES ('辽宁省阜新市');
INSERT INTO `t_location` VALUES ('辽宁省鞍山市');
INSERT INTO `t_location` VALUES ('重庆市');
INSERT INTO `t_location` VALUES ('黑龙江省七台河市');
INSERT INTO `t_location` VALUES ('黑龙江省伊春市');
INSERT INTO `t_location` VALUES ('黑龙江省佳木斯市');
INSERT INTO `t_location` VALUES ('黑龙江省双鸭山市 ');
INSERT INTO `t_location` VALUES ('黑龙江省大庆市');
INSERT INTO `t_location` VALUES ('黑龙江省牡丹江市');
INSERT INTO `t_location` VALUES ('黑龙江省绥化市');
INSERT INTO `t_location` VALUES ('黑龙江省鸡西市');
INSERT INTO `t_location` VALUES ('黑龙江省鹤岗市');
INSERT INTO `t_location` VALUES ('黑龙江省黑河市');
INSERT INTO `t_location` VALUES ('黑龙江省齐齐哈尔市');
